name: our_beautiful_love
description: Love app
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.2.2
  vibration: ^1.9.0
  flutter_emoji: 2.5.1

flutter:
  assets:
    - assets/love.jpg

